version: "3.8"
services:
  react-intro:
    build:
      context: .
      dockerfile: Dockerfile.dev
    cap_add:
      - SYS_ADMIN
    volumes:
      # overwrites node_modules installation with empty folder
      - ./workspace:/usr/workspace
      # overwrite node_modules directly from host with container
      # enables access to node_modules installation in container
      # creates an empty node_modules folder in host
      - /usr/workspace/my-app/node_modules
    working_dir: /usr/workspace
    # prevent container from exiting immediately
    stdin_open: true
    ports:
      - 3000:3000
    # command: npx babel --watch src --out-dir . --presets react-app/prod
