FROM alpine:latest
EXPOSE 3000
RUN apk add --no-cache --update \
 bash sudo npm tree git
WORKDIR /usr/workspace/my-app
COPY /workspace/my-app/package.json /usr/workspace/my-app/package.json
# COPY /workspace/my-app/package-lock.json /usr/workspace/my-app/package-lock.json
RUN npm install
# RUN npm init -y
# RUN npm install babel-cli@6 babel-preset-react-app@3
